name: Learn basic of GitHub Action

on:
  push:
    branches:
      -  main

jobs:
  helloworld:
    runs-on: ubuntu-latest

    steps:
      - name: print hellow
        run: echo "hello world !!"
      - name: print chalo
        run: echo "Chalo world !!" 
        
    
  chaloworld:
      runs-on: ubuntu-latest

      steps:
       - name: print chalo
         run: cat /etc/os-release
          
     
              
